CityBreaks.Web/Models/City.cs
namespace CityBreaks.Web.Models;

public class City
{
    public int Id { get; set; }
    public string Name { get; set; }
    
    public int CountryId { get; set; }
    public Country Country { get; set; }
    
    public List<Property> Properties { get; set; }
}

CityBreaks.Web/Models/Country.cs
namespace CityBreaks.Web.Models;

public class Country
{
    public int Id { get; set; }
    public string CountryCode { get; set; }
    public string CountryName { get; set; }
    
    public List<City> Cities { get; set; }
}

CityBreaks.Web/Models/Property.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace CityBreaks.Web.Models;

public class Property
{
    public int Id { get; set; }

    [Required(ErrorMessage = "O nome é obrigatório")]
    [MaxLength(150, ErrorMessage = "Máximo de 150 caracteres")]
    public string Name { get; set; }

    [Required(ErrorMessage = "O preço por noite é obrigatória")]
    [Range(0.01, double.MaxValue, ErrorMessage = "O preço deve ser um número positivo")]
    public decimal PricePerNight { get; set; }

    [Required(ErrorMessage = "Selecione uma cidade")]
    public int CityId { get; set; }
    [ValidateNever]
    public City City { get; set; }
    
    public DateTime? DeletedAt { get; set; }
}

CityBreaks.Web/Pages/CityDetails.cshtml.cs
using CityBreaks.Web.Data;
using CityBreaks.Web.Models;
using CityBreaks.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CityBreaks.Web.Pages;

public class CityDetailsModel : PageModel
{
    private readonly ICityService _cityService;
    private readonly CityBreaksContext _context;

    public CityDetailsModel(ICityService cityService, CityBreaksContext context)
    {
        _cityService = cityService;
        _context = context;
    }

    public City City { get; set; }

    public async Task<IActionResult> OnGetAsync(string name)
    {
        if (string.IsNullOrEmpty(name)) return NotFound();

        try
        {
            City = await _cityService.GetByNameAsync(name);

            return Page();
        }
        catch (InvalidOperationException)
        {
            return NotFound();
        }
    }

    public async Task<IActionResult> OnPostDeleteAsync(int id, string name)
    {
        var property = await _context.Properties.FindAsync(id);

        if (property == null)
        {
            return NotFound();
        }

        property.DeletedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();

        return RedirectToPage(new { name = name });
    }
}

CityBreaks.Web/Pages/CreateProperty.cshtml.cs
using CityBreaks.Web.Data;
using CityBreaks.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CityBreaks.Web.Pages;

public class CreatePropertyModel : PageModel
{
    private readonly CityBreaksContext _context;

    public CreatePropertyModel(CityBreaksContext context)
    {
        _context = context;
    }

    [BindProperty] public Property Property { get; set; }

    public SelectList Cities { get; set; }

    public async Task OnGetAsync()
    {
        var cities = await _context.Cities
            .ToListAsync();

        Cities = new SelectList(cities, "Id", "Name");
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        await _context.Properties.AddAsync(Property);
        await _context.SaveChangesAsync();

        return RedirectToPage("Index");
    }
}

CityBreaks.Web/Pages/EditProperty.cshtml.cs
using CityBreaks.Web.Data;
using CityBreaks.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CityBreaks.Web.Pages;

public class EditPropertyModel : PageModel
{
    private readonly CityBreaksContext _context;
    public string? FromCityName = String.Empty;

    public EditPropertyModel(CityBreaksContext context)
    {
        _context = context;
    }

    [BindProperty] public Property Property { get; set; }

    public async Task<IActionResult> OnGetAsync(int id)
    {
        Property = (await _context.Properties
            .Include(p => p.City)
            .FirstOrDefaultAsync(p => p.Id == id)!)!;
        if (Property == null)
            return NotFound();

        FromCityName = Property?.City?.Name;

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(int id)
    {
        var propertyToUpdate = await _context.Properties.FindAsync(id);
        if (propertyToUpdate == null)
            return NotFound();

        if (!await TryUpdateModelAsync(
                propertyToUpdate,
                nameof(Property),
                p => p.Name,
                p => p.PricePerNight))
        {
            return Page();
        }

        await _context.SaveChangesAsync();
        return RedirectToPage("Index");
    }
}

CityBreaks.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CityBreaks.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

CityBreaks.Web/Pages/Index.cshtml.cs
using CityBreaks.Web.Models;
using CityBreaks.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CityBreaks.Web.Pages;

public class IndexModel : PageModel
{
    private readonly ICityService _cityService;

    public IndexModel(ICityService cityService)
    {
        _cityService = cityService;
    }

    public List<City> Cities { get; set; }

    public async Task OnGetAsync()
    {
        Cities = await _cityService.GetAllAsync();
    }
}

CityBreaks.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CityBreaks.Web.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

CityBreaks.Web/Pages/CityDetails.cshtml
@page "{name}"
@model CityBreaks.Web.Pages.CityDetailsModel

<h2>Cidade: @Model.City.Name</h2>
<p class="fs-4">País: @Model.City.Country.CountryName</p>

<h4>Propriedades:</h4>
<ul>
    @foreach (var prop in Model.City.Properties)
    {
        <li>
            @prop.Name – R$ @prop.PricePerNight
            <a asp-page="/EditProperty" asp-route-id="@prop.Id">Editar</a>
            <form
                method="post"
                asp-page-handler="Delete"
                asp-route-id="@prop.Id"
                asp-route-name="@Model.City.Name"
                class="d-inline"
            >
                <button type="submit" class="btn btn-link p-0 align-baseline">
                    Excluir
                </button>
            </form>
        </li>
    }
</ul>

<div class="d-flex flex-row align-items-center gap-5">
    <a asp-page="/CreateProperty">Nova Propriedade</a>

    <a asp-page="/Index">Voltar</a>
</div>

CityBreaks.Web/Pages/CreateProperty.cshtml
@page
@model CityBreaks.Web.Pages.CreatePropertyModel

<h1>Cadastrar Propriedade</h1>

<form method="post">
    <div>
        <label>Nome</label><br/>
        <input asp-for="Property.Name"/>
        <span asp-validation-for="Property.Name" class="text-danger"></span>
    </div>

    <div>
        <label>Preço por Noite</label><br/>
        <input asp-for="Property.PricePerNight" type="number" step="0.01"/>
        <span asp-validation-for="Property.PricePerNight" class="text-danger"></span>
    </div>

    <div>
        <label>Cidade</label><br/>
        <select asp-for="Property.CityId" asp-items="Model.Cities">
            <option value="">Selecione uma cidade</option>
        </select>
        <span asp-validation-for="Property.CityId" class="text-danger"></span>
    </div>

    <br/>
    <button type="submit">Salvar</button>
</form>

<a asp-page="/Index">Voltar</a>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

CityBreaks.Web/Pages/EditProperty.cshtml
@page "{id:int}"
@using CityBreaks.Web.Models
@model CityBreaks.Web.Pages.EditPropertyModel

<h1>Editar Propriedade</h1>

<form method="post">
    <div>
        <label>Nome</label><br/>
        <input asp-for="Property.Name"/>
        <span asp-validation-for="Property.Name" class="text-danger"></span>
    </div>

    <div>
        <label>Preço por Noite</label><br/>
        <input asp-for="Property.PricePerNight" type="number" step="0.01"/>
        <span asp-validation-for="Property.PricePerNight" class="text-danger"></span>
    </div>
    
    <br/>
    <button type="submit">Salvar</button>
</form>

<a asp-page="CityDetails" asp-route-name="@Model.FromCityName">Voltar</a>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

CityBreaks.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<main>
    <h1>Cidades Cadastradas</h1>

    @foreach (var city in Model.Cities)
    {
        <div class="border-2 border-info border p-2 mb-1">
            <h2>
                <a asp-page="/CityDetails" asp-route-name="@city.Name">
                    @city.Name <span class="fs-5">- @city.Country.CountryName</span>
                </a>
            </h2>
            <ul class="list-unstyled">
                @foreach (var property in city.Properties)
                {
                    <li>
                        @property.Name - R$ @property.PricePerNight
                    </li>
                }
            </ul>
        </div>
    }
</main>

CityBreaks.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CityBreaks.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CityBreaks.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">CityBreaks.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - CityBreaks.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>